#! /bin/sh
#
# vigilo-correlator       Init script for the Vigilo correlator
#
#
# chkconfig: 345 95 05
# description: Starts and stops the Vigilo correlator
### BEGIN INIT INFO
# Provides: vigilo-correlator
# Required-Start: $network $syslog
# Should-Start: $named
# Required-Stop: $network $syslog
# Should-Stop: $named
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Vigilo correlator
# Description: Vigilo event correlator
### END INIT INFO

# Regler une valeur ici pour lancer le correlateur sous un autre nom
NUM=

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/vigilo-correlator
NAME=vigilo-correlator
TAPNAME=vigilo-correlator
USER=vigilo-correlator

[ -n "$NUM" ] && DOTNUM=.$NUM
LOCK_FILE=/var/lock/subsys/$NAME${DOTNUM}
PID_FILE=/var/run/$NAME/$NAME${DOTNUM}.pid
TWISTD_OPTIONS=""
OPTIONS=""

if [ -f /etc/sysconfig/$NAME ] ; then
    . /etc/sysconfig/$NAME
fi
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
fi

export USER PID_FILE TWISTD_OPTIONS OPTIONS

test -x $DAEMON || exit 0

start() {
    [ -f $LOCK_FILE ] && return

    if [ "$1" = "debug" ]; then
        TWISTD_OPTIONS="$TWISTD_OPTIONS --logfile - -n"
        OUTPUT=""
    else
        TWISTD_OPTIONS="$TWISTD_OPTIONS --logfile /dev/null"
        OUTPUT=">/dev/null 2>&1"
    fi
    [ -n "$NUM" ] && CONFIG="--config /etc/vigilo/correlator/settings-${NUM}.ini"

    echo -n "Starting ${NAME}${NUM}: "
    su -s /bin/bash - $USER -c "$DAEMON --pidfile $PID_FILE $TWISTD_OPTIONS $TAPNAME $CONFIG $OPTIONS $OUTPUT"
    RETVAL=$?
    [ "$1" = "debug" ] && return
    if [ $RETVAL -eq 0 ]; then
        # Wait 3s to make sure it started properly (auth)
        i=0
        while [ $i -lt 3 ]; do
            sleep 1
            if ! pidofproc -p $PID_FILE $DAEMON >/dev/null; then
                RETVAL=1
                break
            fi
            let "i += 1"
            echo -n "."
        done
        [ $RETVAL -eq 0 ] && success || failure
    else
        failure
    fi
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
}

stop() {
    echo -n "Shutting down ${NAME}${NUM}: "
    killproc -p $PID_FILE $NAME
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

reload() {
    echo -n "Reloading ${NAME}${NUM}: "
    killproc -p $PID_FILE $NAME -HUP
    RETVAL=$?
    echo
}



case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status -p $PID_FILE ${NAME}${NUM}
    ;;
    reload)
        reload
    ;;
    restart)
        stop
        start
    ;;
    condrestart)
        if [ -f $LOCK_FILE ]; then
            stop
            start
        fi
    ;;
    debug)
        start "debug"
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|condrestart|status|debug}" >&2
        RETVAL=1
    ;;
esac

exit $RETVAL
